# Generated by Django 5.1.15 on 2026-03-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facets", "0008_alter_division_options_alter_ward_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="polling_place_accessibility",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="division",
            name="polling_place_address",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="division",
            name="polling_place_name",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="division",
            name="polling_place_parking",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="division",
            name="polling_place_zip",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
