# Generated by Django 5.1.15 on 2026-03-03 00:59

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facets", "0009_division_polling_place_accessibility_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CongressionalDistrict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("mpoly", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ("properties", models.JSONField()),
                ("targetable", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
